// Generated by CoffeeScript 2.1.0
(function() {
    $(function() {
        $('.error').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            return $.growl.error({
                message: "QuoteMasterV2!"
            });
        });
        $('.notice').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            return $.growl.notice({
                message: "QuoteMasterV2!"
            });

        });
        return $('.warning').click(function(event) {
            event.preventDefault();
            event.stopPropagation();
            return $.growl.warning({
                message: "QuoteMasterV2!"
            });
        });
    });
}).call(this);